"""Build the Ozzit page's ten worked examples and its index of every named
formula from the pinned release index."""

from __future__ import annotations

import argparse
import csv
import html
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "assets/ozzit-functions-v3.4.2.csv"
EXAMPLES = ROOT / "scripts/ozzit_reference_examples.json"
RECORD = ROOT / "assets/ozzit-reference-v3.4.2.json"
OUTPUT = ROOT / "_includes/ozzit-reference.html"
INDEX_OUTPUT = ROOT / "_includes/ozzit-function-index.html"
SOURCE_URL = "https://github.com/ryanduguid/Ozzit/blob/v3.4.2/src/{module}.txt"


def code(value: str) -> str:
    return html.escape(value).replace("λ", '<span class="function-symbol">λ</span>')


def load_index() -> list[dict[str, str]]:
    with INDEX.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def anchor(function: str) -> str:
    """A fragment id from the function name alone, so it survives module moves."""
    return "oz-" + re.sub(r"[^a-z0-9]", "", function.removeprefix("oz.").lower())


def render_index() -> str:
    rows = load_index()
    if len(rows) != 138 or len({row["function"] for row in rows}) != 138:
        raise ValueError("Expected the 138 unique named formulas in the v3.4.2 index")
    anchors = [anchor(row["function"]) for row in rows]
    if len(set(anchors)) != len(anchors):
        raise ValueError("Two functions share a fragment id")
    modules: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        name = row["function"].removeprefix("oz.")
        signature = row["signature"]
        if not row["function"].startswith("oz.") or not (
            signature == name or signature.startswith(name + "(")
        ):
            raise ValueError(f"{row['function']}: signature does not match its function name")
        modules.setdefault(row["module"], []).append(row)
    parts = ["<!-- Generated by scripts/build_ozzit_reference.py from the pinned index. -->"]
    for module, members in sorted(modules.items(), key=lambda item: (-len(item[1]), item[0])):
        parts.append('<details class="function-index">')
        parts.append(
            f"  <summary><h3>{html.escape(module)}, {len(members)} named formulas</h3></summary>"
        )
        # Safari drops list semantics from an unstyled list unless the role is explicit.
        parts.append('  <ul class="function-index__list" role="list">')
        for row in members:
            call = "oz." + row["signature"]
            parts.append(f'    <li id="{anchor(row["function"])}"><code>{code(call)}</code></li>')
        parts.append("  </ul>")
        source = html.escape(SOURCE_URL.format(module=module), quote=True)
        parts.append(f'  <p><a href="{source}">Released {html.escape(module)} source</a></p>')
        parts.append("</details>")
    return "\n".join(parts) + "\n"


def expected_display(example: dict[str, Any], result: object) -> str:
    rows, columns = example["result_shape"]
    if (
        not isinstance(result, list)
        or len(result) != rows
        or any(not isinstance(row, list) or len(row) != columns for row in result)
    ):
        raise ValueError(f"{example['id']}: native result shape differs from the example")
    values = [value for row in result for value in row]
    template = example["expected_template"]
    if not isinstance(template, str):
        raise ValueError("Expected display template must be text")
    display = template.format(*values, total=sum(values) if "{total" in template else 0)
    if display != example["expected"]:
        raise ValueError(f"{example['id']}: expected display differs from native Excel results")
    return display


def render() -> str:
    rows = load_index()
    functions = {row["function"]: row for row in rows}
    examples = json.loads(EXAMPLES.read_text(encoding="utf-8"))
    record = json.loads(RECORD.read_text(encoding="utf-8"))
    recorded_formulas = {case["id"]: case["formula"] for case in record["cases"]}
    formulas = {example["id"]: example["formula"] for example in examples}
    if formulas != recorded_formulas or set(formulas) != set(record["results"]):
        raise ValueError("Examples need matching native Excel inputs and results")
    if (
        record["workbook_sha256"]
        != "0306793a7e473ce70e78149fea1e107fc0f714d61ab50960c16f6fd528878f6f"
    ):
        raise ValueError("Native results must identify the v3.4.2 release workbook")
    if len(functions) != 138 or len(functions) != len(rows):
        raise ValueError("Expected the 138 unique named formulas in the v3.4.2 index")
    if len(examples) != 10 or len({item["id"] for item in examples}) != 10:
        raise ValueError("Expected ten unique example anchors")
    parts = ["<!-- Generated by scripts/build_ozzit_reference.py; edit the example data. -->"]
    for example in examples:
        display = expected_display(example, record["results"][example["id"]])
        row = functions[example["function"]]
        anchor = html.escape(example["id"], quote=True)
        parts.append(f'<details class="function-reference" id="fn-{anchor}">')
        parts.append(f"  <summary><h3>{html.escape(example['title'])}</h3></summary>")
        parts.append(
            f"  <p><code>{code(row['function'])}</code>: {html.escape(row['description'])}</p>"
        )
        parts.append(
            f"  <p><strong>Signature:</strong> <code>{code(row['signature'])}</code>. Square brackets mark optional arguments.</p>"
        )
        parts.append(
            f'  <pre class="copyable" tabindex="0" role="region" aria-label="{html.escape(example["title"], quote=True)} formula"><code>{code(example["formula"])}</code></pre>'
        )
        parts.append(f"  <p><strong>Expected display:</strong> {html.escape(display)}</p>")
        parts.append(f"  <p><strong>Limits:</strong> {html.escape(example['note'])}</p>")
        parts.append(
            f'  <p><a href="#fn-{anchor}">Link to this example</a> · <a href="https://github.com/ryanduguid/Ozzit/blob/v3.4.2/src/{html.escape(row["module"], quote=True)}.txt">Released formula source<span class="visually-hidden">, {html.escape(example["title"])}</span></a></p>'
        )
        parts.append("</details>")
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {OUTPUT: render(), INDEX_OUTPUT: render_index()}
    if args.write:
        for path, expected in outputs.items():
            path.write_text(expected, encoding="utf-8", newline="\n")
        print("Wrote ten Ozzit function examples and the index of every named formula")
        return 0
    for path, expected in outputs.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            print(f"{path.name} differs: run python scripts/build_ozzit_reference.py --write")
            return 1
    print("Ozzit reference and index match the pinned index and examples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
