"""Build llms-full.txt: every indexable page as plain text, in sitemap order.

Run with --write to regenerate the file, or --check to fail when the committed
file no longer matches the pages it was built from. The text is derived from
the visible <main> content only, so the machine copy can never say more than
the page does.
"""

from __future__ import annotations

import html as html_lib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import seo_core as core  # noqa: E402

ROOT = core.ROOT
OUTPUT = ROOT / "llms-full.txt"
SITE = "https://duguid.com.au"
MAIN_PATTERN = re.compile(r"<main\b[^>]*>(.*?)</main>", re.S | re.I)
# Only wayfinding navigation is dropped: breadcrumbs and on-this-page contents.
# Navigation that carries content (tool categories, related pages, actions,
# source-only distributions) stays in the text.
WAYFINDING_NAV_PATTERN = re.compile(
    r'<nav\b[^>]*\bclass="[^"]*\barticle-(?:crumb|toc)\b[^"]*"[^>]*>.*?</nav>',
    re.S | re.I,
)
PRE_PATTERN = re.compile(r"<pre\b[^>]*>(.*?)</pre>", re.S | re.I)
HEADING_PATTERN = re.compile(r"<h([1-4])\b[^>]*>(.*?)</h\1>", re.S | re.I)
BLOCK_TAGS = (
    "p|div|section|article|header|footer|ul|ol|dl|dt|dd|blockquote|table|"
    "thead|tbody|tr|figure|figcaption|details|summary|br|hr"
)
BLOCK_PATTERN = re.compile(rf"</?(?:{BLOCK_TAGS})\b[^>]*>", re.I)
LI_PATTERN = re.compile(r"<li\b[^>]*>", re.I)
CELL_PATTERN = re.compile(r"</t[dh]>\s*<t[dh]\b[^>]*>", re.S | re.I)
TAG_PATTERN = re.compile(r"<[^>]+>")
HEADER = (
    "# duguid.com.au, full text\n\n"
    "Every indexable page of https://duguid.com.au/ as plain text, in sitemap "
    "order, built from the visible main content of each page. The short index "
    "is https://duguid.com.au/llms.txt. Nothing here is tax, legal or financial "
    "advice; verify figures against current guidance before relying on them.\n\n"
    "Generated by scripts/build_llms_full.py. Do not edit by hand.\n"
)


def page_path(url: str) -> Path:
    rel = url.removeprefix(SITE).strip("/")
    return ROOT / (f"{rel}/index.html" if rel else "index.html")


def block_kind(block: str) -> str:
    if block.startswith("- "):
        return "item"
    if " | " in block:
        return "row"
    return "text"


def preformatted(inner: str) -> str:
    """A <pre> block as a fenced block with its line breaks and indentation kept."""
    lines = html_lib.unescape(TAG_PATTERN.sub("", inner)).strip("\n").splitlines()
    return "```\n" + "\n".join(line.rstrip() for line in lines) + "\n```"


def main_text(html: str) -> str:
    matches = MAIN_PATTERN.findall(html)
    if len(matches) != 1:
        raise SystemExit("llms-full: page must have exactly one <main>")
    body = core.visible_html(WAYFINDING_NAV_PATTERN.sub(" ", matches[0]))
    pres: list[str] = []

    def hold_pre(match: re.Match[str]) -> str:
        pres.append(preformatted(match.group(1)))
        return f"\n\nPREFORMATTED-{len(pres) - 1}\n\n"

    body = PRE_PATTERN.sub(hold_pre, body)
    body = HEADING_PATTERN.sub(lambda m: f"\n\n{'#' * int(m.group(1))} {m.group(2)}\n\n", body)
    body = LI_PATTERN.sub("\n\n- ", body)
    body = CELL_PATTERN.sub(" | ", body)
    body = BLOCK_PATTERN.sub("\n\n", body)
    # Adjacent inline elements such as two links keep a space between them.
    body = body.replace("><", "> <")
    body = html_lib.unescape(TAG_PATTERN.sub("", body))
    blocks = [re.sub(r"\s+", " ", block).strip() for block in re.split(r"\n\s*\n", body)]
    text = ""
    previous = "text"
    for block in filter(None, blocks):
        kind = block_kind(block)
        joined = kind != "text" and kind == previous
        text += ("\n" if joined else "\n\n") + block
        previous = kind
    text = re.sub(r"PREFORMATTED-(\d+)", lambda m: pres[int(m.group(1))], text)
    return text.strip()


def build() -> str:
    parts = [HEADER]
    for url in core.sitemap_urls(ROOT):
        html = page_path(url).read_text(encoding="utf-8")
        title = html_lib.unescape(re.search(r"<title>(.*?)</title>", html, re.S).group(1)).strip()
        description = core.meta(html, "name", "description") or ""
        parts.append(f"---\n\n# {title}\n\nSource: {url}\n\n> {description}\n\n{main_text(html)}\n")
    return "\n".join(parts)


def main(argv: list[str]) -> int:
    built = build()
    if "--write" in argv:
        OUTPUT.write_text(built, encoding="utf-8", newline="\n")
        print(f"llms-full.txt written ({built.count('Source: ')} pages)")
        return 0
    current = OUTPUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUTPUT.is_file() else ""
    if current != built:
        print("llms-full.txt is stale: run python scripts/build_llms_full.py --write")
        return 1
    print(f"llms-full.txt matches its pages ({built.count('Source: ')} pages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
