"""Build the ten Ozzit reference entries from the pinned release index."""

from __future__ import annotations

import argparse
import csv
import html
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "assets/ozzit-functions-v3.4.2.csv"
EXAMPLES = ROOT / "scripts/ozzit_reference_examples.json"
RECORD = ROOT / "assets/ozzit-reference-v3.4.2.json"
OUTPUT = ROOT / "_includes/ozzit-reference.html"


def code(value: str) -> str:
    return html.escape(value).replace("λ", '<span class="function-symbol">λ</span>')


def expected_display(example: dict[str, Any], result: object) -> str:
    rows, columns = example["result_shape"]
    if (
        not isinstance(result, list)
        or len(result) != rows
        or any(not isinstance(row, list) or len(row) != columns for row in result)
    ):
        raise ValueError(f"{example['id']}: native result shape differs from the example")
    values = [value for row in result for value in row]
    template = example["expected_template"]
    if not isinstance(template, str):
        raise ValueError("Expected display template must be text")
    display = template.format(*values, total=sum(values) if "{total" in template else 0)
    if display != example["expected"]:
        raise ValueError(f"{example['id']}: expected display differs from native Excel results")
    return display


def render() -> str:
    with INDEX.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    functions = {row["function"]: row for row in rows}
    examples = json.loads(EXAMPLES.read_text(encoding="utf-8"))
    record = json.loads(RECORD.read_text(encoding="utf-8"))
    recorded_formulas = {case["id"]: case["formula"] for case in record["cases"]}
    formulas = {example["id"]: example["formula"] for example in examples}
    if formulas != recorded_formulas or set(formulas) != set(record["results"]):
        raise ValueError("Examples need matching native Excel inputs and results")
    if (
        record["workbook_sha256"]
        != "0306793a7e473ce70e78149fea1e107fc0f714d61ab50960c16f6fd528878f6f"
    ):
        raise ValueError("Native results must identify the v3.4.2 release workbook")
    if len(functions) != 138 or len(functions) != len(rows):
        raise ValueError("Expected the 138 unique named formulas in the v3.4.2 index")
    if len(examples) != 10 or len({item["id"] for item in examples}) != 10:
        raise ValueError("Expected ten unique example anchors")
    parts = ["<!-- Generated by scripts/build_ozzit_reference.py; edit the example data. -->"]
    for example in examples:
        display = expected_display(example, record["results"][example["id"]])
        row = functions[example["function"]]
        anchor = html.escape(example["id"], quote=True)
        parts.append(f'<details class="function-reference" id="fn-{anchor}">')
        parts.append(f"  <summary><h3>{html.escape(example['title'])}</h3></summary>")
        parts.append(
            f"  <p><code>{code(row['function'])}</code>: {html.escape(row['description'])}</p>"
        )
        parts.append(
            f"  <p><strong>Signature:</strong> <code>{code(row['signature'])}</code>. Square brackets mark optional arguments.</p>"
        )
        parts.append(
            f'  <pre class="copyable" tabindex="0" role="region" aria-label="{html.escape(example["title"], quote=True)} formula"><code>{code(example["formula"])}</code></pre>'
        )
        parts.append(f"  <p><strong>Expected display:</strong> {html.escape(display)}</p>")
        parts.append(f"  <p><strong>Limits:</strong> {html.escape(example['note'])}</p>")
        parts.append(
            f'  <p><a href="#fn-{anchor}">Link to this example</a> · <a href="https://github.com/ryanduguid/Ozzit/blob/v3.4.2/src/{html.escape(row["module"], quote=True)}.txt">Released formula source</a></p>'
        )
        parts.append("</details>")
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
        print("Wrote ten Ozzit function examples")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
        print("Ozzit reference differs: run python scripts/build_ozzit_reference.py --write")
        return 1
    print("Ozzit reference matches the pinned index and examples")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
